name: Install Swift on Linux
description: Installs a Swift toolchain on Linux
author: ser.soft GmbH
inputs:
  release-version:
    description: The (released) Swift version (e.g. 5.3.2) to install. If given, `branch-name` and `version-tag` are ignored. If `github-token` is also set, the action will automatically resolve it to the latest matching version (e.g. 5.3.3 for 5.3).
    required: false
  branch-name:
    description: The branch of the Swift version to install (e.g. swift-5.2.1-release). Required if `release-version` is not set!
    required: false
  version-tag:
    description: The version tag of the Swift version to install (e.g. swift-5.2.1-RELEASE). Required if `release-version` is not set!
    required: false
  platform:
    description: The platform for which to install the Swift version (e.g. ubuntu18.04). Note that the github-actions notations with a dash (e.g. ubuntu-20.04) is also valid.
    required: false
  skip-apt:
    description: Whether or not the installation of dependencies (via apt) should be skipped.
    required: false
    default: 'false'
  github-token:
    description: Only required if `release-version` should automatically resolve to the newest matching version. Can be set to `secrets.GITHUB_TOKEN`.
    required: false
outputs:
  install-path:
    description: The path where Swift was installed.
  full-version:
    description: The full version that was installed (e.g. swift-5.4.2-RELEASE).
runs:
  using: node12
  main: dist/index.js
branding:
  color: orange
  icon: cpu
