name: Install Swift on Linux
description: Installs a Swift toolchain on Linux
author: ser.soft GmbH
inputs:
  release-version:
    description: The (released) Swift version (e.g. 5.8.1) to install. If given, `branch-name` and `version-tag` are ignored. If `github-token` is also set, the action will automatically resolve it to the latest matching version (e.g. 5.8.1 for 5.8).
    required: false
  branch-name:
    description: The branch of the Swift version to install (e.g. swift-5.8.1-release). Required if `release-version` is not set!
    required: false
  version-tag:
    description: The version tag of the Swift version to install (e.g. swift-5.8.1-RELEASE). Required if `release-version` is not set!
    required: false
  platform:
    description: The platform for which to install the Swift version (e.g. ubuntu22.04). Note that the github-actions notations with a dash (e.g. ubuntu-22.04) is also valid.
    required: false
  skip-dependencies:
    description: Whether or not the installation of dependencies (currently via apt) should be skipped.
    required: false
    default: 'false'
  skip-apt:
    description: Whether or not the installation of dependencies (via apt) should be skipped.
    required: false
    default: 'false'
    deprecationMessage: Use `skip-dependencies` instead.
  github-token:
    description: Only required if `release-version` should automatically resolve to the newest matching version. Can be set to `secrets.GITHUB_TOKEN`.
    required: false
    default: ${{ github.token }}
outputs:
  install-path:
    description: The path where Swift was installed.
  full-version:
    description: The full version that was installed (e.g. swift-5.8.1-RELEASE).
runs:
  using: node16
  main: dist/index.js
branding:
  color: orange
  icon: cpu
