name: Master Deploy

on:
  push:
    branches: [ master ]
    paths-ignore: [ 'dist/*.js' ]

jobs:
  deploy-action-code:
    runs-on: ubuntu-latest
    steps:
      - name: Install depenedencies
        run: sudo npm i -g @zeit/ncc typescript
      - uses: actions/checkout@v2.3.4
        with:
          token: ${{secrets.BOT_TOKEN}}
      - name: Generate action code
        run: npm run deploy
      - name: Configure repository
        run: |
          git config user.name "${{secrets.BOT_USERNAME}}"
          git config user.email "${{secrets.BOT_USERNAME}}@users.noreply.github.com"
      - name: Commit changes
        run: |
          if ! git diff --exit-code --quiet; then
            git add .
            git commit -m "[AUTO] Update generated code"
            git push
          fi

  test-release-master:
    needs: deploy-action-code
    strategy:
      matrix:
        swift-version: [5.3, 5.2.5]
        os-version: ['ubuntu-20.04', 'ubuntu-18.04']
        token: ['']
        include:
          - swift-version: 5.1
            os-version: ubuntu-18.04
            token: ''
          - swift-version: 5.4
            os-version: ubuntu-20.04
            token: ${{secrets.GITHUB_TOKEN}}
    runs-on: ${{matrix.os-version}}
    steps:
      - uses: sersoft-gmbh/SwiftyActions@master
        id: install-swift
        with:
          release-version: ${{matrix.swift-version}}
          platform: ${{matrix.os-version}}
          github-token: ${{matrix.token}}
      - name: Check installed path
        run: test -d ${{steps.install-swift.outputs.install-path}}
      - name: Check installed version
        run: swift --version | grep -q ${{matrix.swift-version}}

  test-branch-master:
    needs: deploy-action-code
    strategy:
      matrix:
        swift-version: [5.3, 5.2.5]
        os-version: ['ubuntu-20.04', 'ubuntu-18.04']
        include:
          - swift-version: 5.1
            os-version: ubuntu-18.04
    runs-on: ${{matrix.os-version}}
    steps:
      - uses: sersoft-gmbh/SwiftyActions@master
        id: install-swift
        with:
          branch-name: swift-${{matrix.swift-version}}-release
          version-tag: swift-${{matrix.swift-version}}-RELEASE
          platform: ${{matrix.os-version}}
      - name: Check installed path
        run: test -d ${{steps.install-swift.outputs.install-path}}
      - name: Check installed version
        run: swift --version | grep -q ${{matrix.swift-version}}

  test-release-noplatform-master:
    needs: deploy-action-code
    strategy:
      matrix:
        os-version: [ 'ubuntu-20.04', 'ubuntu-18.04' ]
        token:
          - ''
          - ${{secrets.GITHUB_TOKEN}}
    runs-on: ${{matrix.os-version}}
    steps:
      - uses: sersoft-gmbh/SwiftyActions@master
        id: install-swift
        with:
          release-version: 5.4
          github-token: ${{matrix.token}}
      - name: Check installed path
        run: test -d ${{steps.install-swift.outputs.install-path}}
      - name: Check installed version
        run: swift --version | grep -q '5.4'
